-- User profiles 
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'registered_user'
    check (role in ('registered_user', 'system_admin')),
  created_at timestamptz not null default now()
);

-- News categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

-- News articles
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id),
  category_id bigint references public.categories(id),
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  featured_image_url text,
  view_count integer not null default 0,
  reaction_count integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

-- Registered Users' selected categories
create table if not exists public.user_preferences (
  user_id uuid references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, category_id)
);

-- Individual article views used to prevent repeated counting
create table if not exists public.article_views (
  article_id bigint not null
    references public.articles(id) on delete cascade,
  viewer_identifier text not null,
  viewed_on date not null default current_date,
  viewed_at timestamptz not null default now(),
  primary key (article_id, viewer_identifier, viewed_on)
);