
-- Feature 1: News Categorisation and Tagging


-- 1. Tags
-- Stores tags that can be assigned to news articles.

create table if not exists public.tags (
    id bigint generated by default as identity primary key,
    name text unique not null,
    created_at timestamptz not null default now()
);


-- 2. Article Categories
-- Junction table allowing articles to have multiple
-- categories.

create table if not exists public.article_categories (
    article_id bigint not null
        references public.articles(id)
        on delete cascade,

    category_id bigint not null
        references public.categories(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (article_id, category_id)
);


-- 3. Migrate Existing Article Categories
-- Copies existing articles.category_id relationships into
-- the new article_categories junction table.
--
-- articles.category_id is intentionally NOT removed yet
-- because existing features still depend on it

insert into public.article_categories (
    article_id,
    category_id
)
select
    id,
    category_id
from public.articles
where category_id is not null
on conflict do nothing;

-- 4. Article Tags
-- Junction table allowing articles to have multiple tags.

create table if not exists public.article_tags (
    article_id bigint not null
        references public.articles(id)
        on delete cascade,

    tag_id bigint not null
        references public.tags(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (article_id, tag_id)
);


-- 5. Prevent Case-Insensitive Duplicate Names

create unique index if not exists categories_name_unique_lower
on public.categories (lower(name));

create unique index if not exists tags_name_unique_lower
on public.tags (lower(name));

-- 6. System Admin Check
-- Helper function used by RLS policies.

create or replace function public.is_system_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'system_admin'
    );
$$;

-- 7. Enable Row Level Security

alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.article_categories enable row level security;
alter table public.article_tags enable row level security;


-- CATEGORY POLICIES

-- 8. Guests and Registered Users Can View Categories

drop policy if exists "Anyone can view categories"
on public.categories;

create policy "Anyone can view categories"
on public.categories
for select
to anon, authenticated
using (true);

-- 9. System Admin Can Create Categories

drop policy if exists "System Admin can create categories"
on public.categories;

create policy "System Admin can create categories"
on public.categories
for insert
to authenticated
with check (
    public.is_system_admin()
);


-- 10. System Admin Can Edit Categories

drop policy if exists "System Admin can edit categories"
on public.categories;

create policy "System Admin can edit categories"
on public.categories
for update
to authenticated
using (
    public.is_system_admin()
)
with check (
    public.is_system_admin()
);


-- 11. System Admin Can Delete Categories

drop policy if exists "System Admin can delete categories"
on public.categories;

create policy "System Admin can delete categories"
on public.categories
for delete
to authenticated
using (
    public.is_system_admin()
);


-- TAG POLICIES

-- 12. Guests and Registered Users Can View Tags

drop policy if exists "Anyone can view tags"
on public.tags;

create policy "Anyone can view tags"
on public.tags
for select
to anon, authenticated
using (true);

-- 13. System Admin Can Create Tags

drop policy if exists "System Admin can create tags"
on public.tags;

create policy "System Admin can create tags"
on public.tags
for insert
to authenticated
with check (
    public.is_system_admin()
);

-- 14. System Admin Can Edit Tags

drop policy if exists "System Admin can edit tags"
on public.tags;

create policy "System Admin can edit tags"
on public.tags
for update
to authenticated
using (
    public.is_system_admin()
)
with check (
    public.is_system_admin()
);

-- 15. System Admin Can Delete Tags

drop policy if exists "System Admin can delete tags"
on public.tags;

create policy "System Admin can delete tags"
on public.tags
for delete
to authenticated
using (
    public.is_system_admin()
);

-- ARTICLE CATEGORY POLICIES

-- 16. Guests and Registered Users Can View
-- Article-Category Relationships

drop policy if exists "Anyone can view article categories"
on public.article_categories;

create policy "Anyone can view article categories"
on public.article_categories
for select
to anon, authenticated
using (true);

-- 17. System Admin Can Manage Article Categories

drop policy if exists "System Admin can manage article categories"
on public.article_categories;

create policy "System Admin can manage article categories"
on public.article_categories
for all
to authenticated
using (
    public.is_system_admin()
)
with check (
    public.is_system_admin()
);


-- ARTICLE TAG POLICIES

-- 18. Guests and Registered Users Can View
-- Article-Tag Relationships

drop policy if exists "Anyone can view article tags"
on public.article_tags;

create policy "Anyone can view article tags"
on public.article_tags
for select
to anon, authenticated
using (true);

-- 19. System Admin Can Manage Article Tags

drop policy if exists "System Admin can manage article tags"
on public.article_tags;

create policy "System Admin can manage article tags"
on public.article_tags
for all
to authenticated
using (
    public.is_system_admin()
)
with check (
    public.is_system_admin()
);